### ISSUE TITLE
incompatibility with demeter

### ISSUE THREAD

**Issue by Linguardium** [TerraformersMC/Terraform#10]
recent versions added a mixin to cropblock which is interfering with demeter's mixin. 

this causes crashes on launch, sadly and requires me to revert versions until it is resolved :(

https://paste.dimdev.org/ozonazijev.cpp

**Comment by ghost** [comment]
As the developer of Demeter, I would just stop using Demeter in the short term, it likely isn't going to be updated for a minute as my priorities lie in helping develop new biomes for Terraformers :)

**Comment by Linguardium** [comment]
wow, didnt realize you would respond, i let vanilla+ biomes know (As they are the only ones i know of using the new version atm) as well as opened an issue on your mod.
Thanks for the heads up

**Comment by NeusFear** [comment]
This will hopefully be fixed when the Mixin used is merged into fabric API. Either way, we're probably going to mark this as wontfix until the API is merged.

**Comment by ghost** [comment]
This should actually be fixed now that the rewritten version of Demeter doesn't modify farmland at all
