### ISSUE TITLE
Terraform boats break differently to vanilla boats

### ISSUE THREAD

**Issue by SollyW** [TerraformersMC/Terraform#12]
Terraform boats break when falling, while vanilla boats do not. See video.
https://www.youtube.com/watch?v=fianC98KGY0

**Comment by dvitski** [comment]
[`TerraformBoatEntity`#L70-L95](https://github.com/TerraformersMC/Terraform/blob/1.16/src/main/java/com/terraformersmc/terraform/entity/TerraformBoatEntity.java#L70-L95)

**Comment by SollyW** [comment]
A "cleaner" way to add boats is to use 🍫 to add to the enum. Needs 🍫 though.

**Comment by Prospector** [comment]
Fixed
