### ISSUE TITLE
Terraform Leavs and Leaf Pile Blocks should break with hoe tool

### ISSUE THREAD

**Issue by NeusFear** [TerraformersMC/Terraform#13]
In 1.16 Minecraft made the main tool for breaking leaves the hoe, should be a simple fix by adding it to the BlockSettings of these two blocks.

**Comment by coderbot16** [comment]
It seems like this should be the responsibility of whatever mod is registering the leaves and leaf pile blocks... Terraform just passes through the BlockSettings and doesn't touch it.

**Comment by NeusFear** [comment]
agreed, especially since in 1.17 this is finally done with json
