### ISSUE TITLE
ExtendedLeavesBlock dos not extend LeavesBlock

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Terraform#17]
This can cause some compatibility issues with mixins (came across this issue with one of my mods)

It would also probably be easier since much of the code is the same. Can always override it if not :P

**Comment by Linguardium** [comment]
would it be possible to add it to the leaves tag and just check if its in the minecraft:leaves tag rather than relying on hardcoded classes

**Comment by ghost** [comment]
> would it be possible to add it to the leaves tag and just check if its in the minecraft:leaves tag rather than relying on hardcoded classes

not sure how to do that, but that may make more sense

**Comment by Linguardium** [comment]
add your leaf block (or a reference to your own leaf tag) to /resources/data/minecraft/tags/blocks/leaves.json

in code, `state.isIn(BlockTags.LEAVES)`

**Comment by ghost** [comment]
> add your leaf block (or a reference to your own leaf tag) to /resources/data/minecraft/tags/blocks/leaves.json
> 
> in code, `state.isIn(BlockTags.LEAVES)`

I'm adding a block property to all leaves, it just wouldn't rly make sense, idk

**Comment by Linguardium** [comment]
In the interim of the discussion, you can still use a mixin plugin to disable/enable a mixin into the ExtendedLeavesBlock class depending on whether Terraform is loaded

you could create a separate mixin and mixin config file for the compatibility, then apply a mixin plugin similar to this https://github.com/AllOfFabric/BeeProductive/tree/master/src/main/java/io/github/alloffabric/beeproductive/hooks/BeeBetterMixinPlugin.java (or granularly check for the existance of compat necessary mods and add their enable their mixins appropriately)

**Comment by NeusFear** [comment]
We can't extend LeavesBlock because we don't want to replace all Leaves with our modified distance property. I would recommend you add a compatibility layer to terraform mods to add your property, it should be applicable to ExtendedLeaves blocks because they are similar. We wont be making ExtendedLeavesBlock extend LeavesBlock.

**Comment by ghost** [comment]
> In the interim of the discussion, you can still use a mixin plugin to disable/enable a mixin into the ExtendedLeavesBlock class depending on whether Terraform is loaded
> 
> you could create a separate mixin and mixin config file for the compatibility, then apply a mixin plugin similar to this https://github.com/AllOfFabric/BeeProductive/tree/master/src/main/java/io/github/alloffabric/beeproductive/hooks/BeeBetterMixinPlugin.java (or granularly check for the existance of compat necessary mods and add their enable their mixins appropriately)

alright, i can do that. Thanks :)
