### ISSUE TITLE
TerraformWallSignBlock doesn't delegate loot tables to parent block type

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Terraform#21]
In vanilla the WallSignBlock delegates its loot table to the SignBlock that it is constructed with, this means that there is no "jungle_wall_sign.json" (etc.) loot table because it's inferred from the parent. This is not the case with the TerraformWallSignBlock and should probably be fixed idk.

**Comment by haykam821** [comment]
I think it makes sense for mods constructing `TerraformWallSignBlock` instances to call the `dropsLike` method manually, like with other block settings:

```java
public static final Block FIR_SIGN = register("fir_sign", new TerraformSignBlock(FIR_SIGN_TEXTURE, FabricBlockSettings.copyOf(Blocks.OAK_SIGN)));
public static final Block FIR_WALL_SIGN = register("fir_wall_sign", new TerraformWallSignBlock(FIR_SIGN_TEXTURE, FabricBlockSettings.copyOf(Blocks.OAK_WALL_SIGN).dropsLike(FIR_SIGN)));
```

Automatically calling `dropsLike` would also prevent a situation where a sign needs a different loot table for its wall variant.
