### ISSUE TITLE
Audit dirt mixins to make sure that all hardcoded cases of dirt usage are covered

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Terraform#22]
For example, melons / pumpkins stems can't place pumpkins / melons on to andisol blocks.

**Comment by gniftygnome** [comment]
While testing this I discovered although stems place onto our dirt, grass, and podzol, they do not place onto our farmland, which they should (and convert it to dirt, like vanilla).  I'll fix that and then resolve this issue.
