### ISSUE TITLE
kept crashing because of terraform-dirt?

### ISSUE THREAD

**Issue by lazerus609** [TerraformersMC/Terraform#23]
i dont know how to read crash reports/logs so im goin off of what someone told me to do (which is post the log here)
here is the log:
https://pastebin.com/gjAbf6KP
i got my modpack to work again after removing terraform and terrestria but cinderscapes was perfectly fine ;.;
(im new to github so idk how to use this)

**Comment by coderbot16** [comment]
Some of your mods are outdated. You need to make sure that traverse, terrestria, and cinderscapes are all on the latest versions available for 1.16.3.
