### ISSUE TITLE
Is Terraform the same (or more) as Shapes?

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Terraform#29]
On https://github.com/TerraformersMC/Shapes you can read that "Shapes is now part of Terraform". Does this mean that devs can easily migrate to Terraform? I'm asking because Astromine is depending on Shapes but since it's not developed anymore they should migrate to something else right?

**Comment by NeusFear** [comment]
Terraform is now modular just like fabric api so if you only need the shapes part you can just include that module. But yes I would recommend using the terraform module
