### ISSUE TITLE
Terraform Signs render as Oak Signs

### ISSUE THREAD

**Issue by MoriyaShiine** [TerraformersMC/Terraform#42]
As of version 2.0.1, registering a new TerraformSignBlock and registering the sign texture to the sign atlas still only renders the sign as an Oak Sign.

Example:
https://github.com/MoriyaShiine/bewitchment/blob/388aec0ab7412e92bd820e340f5fe777e00fe2ed/src/main/java/moriyashiine/bewitchment/common/registry/BWObjects.java#L103
https://github.com/MoriyaShiine/bewitchment/blob/388aec0ab7412e92bd820e340f5fe777e00fe2ed/src/main/java/moriyashiine/bewitchment/client/BewitchmentClient.java#L250

![2021-07-29_20 02 09](https://user-images.githubusercontent.com/45156123/127584199-a70183c0-a32f-46e0-b4ed-6dcbfd27a2c9.png)

**Comment by ghost** [comment]
Can confirm, I've been meaning to report this. I've been experiencing the same thing in Cinderscapes dev
