### ISSUE TITLE
Wood API breaks on 1.19

### ISSUE THREAD

**Issue by Oliver-makes-code** [TerraformersMC/Terraform#55]
The wood API breaks on 1.19, due to no `<init>` method being found in BoatEntityRenderer with the correct method signature

**Comment by haykam821** [comment]
Are you using Terraform 4.0.0, which corresponds to Minecraft 1.19? At the time, the latest version for Minecraft 1.19 is `4.0.0-alpha.4`.

**Comment by Oliver-makes-code** [comment]
Ah, I did not see that
