### ISSUE TITLE
Redirect Conflict with MoreTags

### ISSUE THREAD

**Issue by Kneelawk** [TerraformersMC/Terraform#61]
# The Issue
Both MoreTags and Terraformers-Dirt-API redirect the `BlockState.isOf` call in `CropBlock.getAvailableMoisture`, leading to a redirect conflict.

# Tested Mod Versions
* [MoreTags](https://github.com/gudenau/minecraft-MoreTags) `v3.0.3` (latest as of this issue)
* [Terraformers-Dirt-API](https://github.com/TerraformersMC/Terraform) `v3.1.0` and `v4.1.1` (latest as of this issue) (likely affects all versions in between)

# Crash Logs
Crash logs using Terraformers-Dirt-API `v3.1.0`: https://pastebin.com/xGVeGdjj
Crash logs using Terraformers-Dirt-API `v4.1.1`: https://pastebin.com/0P6yVzSQ

# Potential Solution
Given that both of these redirects appear to be for the purpose of checking if a potential farmland block is part of block tag. Either one of these mods could depend on the other or both could use a less-invasive mixin type like one of the mixins from [MixinExtras](https://github.com/LlamaLad7/MixinExtras).

**Comment by Kneelawk** [comment]
Issue on MoreTags repository: https://github.com/gudenau/minecraft-MoreTags/issues/22

**Comment by gniftygnome** [comment]
I can modify our mixin to prevent the crash, but unless there are changes to More Tags, custom Terraform API farmland will be incompatible with More Tags, so the recommendation (for Terrestria users at least) will remain to not use More Tags unless that mod improves its compatibility.

**Comment by gniftygnome** [comment]
Fixed (in our mods beginning with 1.19.4) by JiJing MixinExtras and using WrapOperation ... we'll also conflict with MoreTags until they resolve both aspects of https://github.com/gudenau/minecraft-MoreTags/issues/22
