### ISSUE TITLE
Terraform Dirt mixin broken by More Slabs, Stairs, and Walls mixin

### ISSUE THREAD

**Issue by Gamemassa** [TerraformersMC/Terraform#62]
I got a crash report recently and from reading through the report, I thought maybe it had to do with another mod (since I saw that mod pop up too) so I posted it in that mod's GitHub page, but their team was kind enough to clarify that the bug actually appears to be a mixin from Terraform Dirt failing to apply correctly, possibly due to a conflict with something else. Here is the crash report so you guys can take a look too.

https://gist.github.com/Gamemassa/fb7ee98e9b1d12f03b0948203a6a48e3

**Comment by gniftygnome** [comment]
You mean the other mod ham-fistedly replaces something we're mixing in to and since it's our mod that breaks they think it's our problem?  How kind.  :P

Edit:  I figured out you probably asked the Moonlight lib folks and if so yeah, I don't think it's anything to do with them.

I am having a hard time figuring out what mod `games.twinhead.mixin.SpreadableBlockMixin` is actually from; if you have an idea could you let me know?  It would be easier to see what's going on if I could look at their source.

**Comment by gniftygnome** [comment]
So I don't have to copy this out into a text editor again:

```
[main/ERROR]: Mixin apply for mod terraform-dirt-api-v1 failed
    mixins.terraform-dirt.json:MixinSpreadableBlock from mod terraform-dirt-api-v1 ->
        net.minecraft.class_2500: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE")
            on net/minecraft/class_2500::onScheduledTick with priority 1000
    cannot inject into
        net/minecraft/class_2500::method_9514(Lnet/minecraft/class_2680;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Lnet/minecraft/class_5819;)V
            merged by games.twinhead.mixin.SpreadableBlockMixin with priority 1000
    [PREINJECT Applicator Phase ->
        mixins.terraform-dirt.json:MixinSpreadableBlock from mod terraform-dirt-api-v1
            -> Prepare Injections ->  ->
                handler$fag000$onScheduledTick(Lnet/minecraft/class_2680;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Lnet/minecraft/class_5819;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_2680;ILnet/minecraft/class_2338;)V
                -> Prepare]
```

**Comment by Gamemassa** [comment]
> You mean the other mod ham-fistedly replaces something we're mixing in to and since it's our mod that breaks they think it's our problem? How kind. :P

- Yes, apologies for the accidental ambiguity. I did originally send this to the Moonlight team, and after reading their response, I didn't think it was anything to do with them so I chose not to name-drop them here.

> 
> Edit: I figured out you probably asked the Moonlight lib folks and if so yeah, I don't think it's anything to do with them.
> 
> I am having a hard time figuring out what mod `games.twinhead.mixin.SpreadableBlockMixin` is actually from; if you have an idea could you let me know? It would be easier to see what's going on if I could look at their source.

- I'll do a little digging as far as the twinhead.mixin.SpreadableBlockMixin and I'll let you know what I find.
--Edit: After googling what "spreadable block" means, my guess is that this "twinhead" one is either from Oh The Biomes You'll Go or BetterNether, because those are the only two mods I can think of in my list that are adding spreadable blocks.

**Comment by gniftygnome** [comment]
I know (from all the bug reports about feature order cycles) there are plenty of folks running our mods with BYG so I doubt it's them.  On the other hand, nothing in the Better Nether source appears to mention twinhead.

Is your modpack downloadable by any chance?  I can use unzip and grep to look for classes starting with games.twinhead in the jars...

**Comment by Gamemassa** [comment]
Um, it's a custom modpack I've put together, so no it's not readily downloadable, but I guess technically I could _make it downloadable_ (as in throw all the mods in a zip file and attach it here or something). 

Also, what does "grep" mean?

**Comment by gniftygnome** [comment]
> Also, what does "grep" mean?

It's a UNIX command for quickly finding strings or regular expressions in text.
https://www.gnu.org/software/grep/

**Comment by Gamemassa** [comment]
Here's my modpack. (Let me know if the link doesn't work for some reason)
https://www.dropbox.com/s/qqwv960qimhyig8/Gamemassa%27s%20Minecraft%20Modpack.zip?dl=0

**Comment by gniftygnome** [comment]
The mod in question is `More Slabs, Stairs, and Walls`.  It appears the author has deleted the mod's source from GitHub...

```bash
imperator:~$ mkdir testytest
imperator:~$ cd testytest
imperator:~/testytest$ ls
imperator:~/testytest$ unzip ~/Gamemassa\'s\ Minecraft\ Modpack.zip 
# [...]
imperator:~/testytest$ ls | while read FILE; do unzip -c "${FILE}" | fgrep games.twinhead && echo "${FILE}"; done
grep: (standard input): binary file matches
more_slabs_stairs_and_walls-2.0.0-1.19.2.jar
imperator:~/testytest$ 
```

**Comment by Gamemassa** [comment]
Hmm, that's weird. I wonder why Nibaru did that. Anyway, I'll just deactivate that mod for now.

**Comment by gniftygnome** [comment]
I'll leave this issue open for now, in case other folks have this problem.  We could try to get ahold of the source and see if we could work around the problem, but I think the real issue is the other mod is using a (probably unnecessarily) overly broad mixin; we might not be able to work around it unless we tried to overpower their mixin with ours, which is a losing game.

**Comment by gniftygnome** [comment]
Nibaru has restored the source of the More Slabs, Stairs, and Walls mod [in GH](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls) and also [released a fix](https://modrinth.com/mod/moressw/version/2.0.2-1.19.2) (judging by the changelog) for the compatibility issue.  Thanks to them and I am closing this issue.
