### ISSUE TITLE
Extended leaves cannot be waterlogged

### ISSUE THREAD

**Issue by haykam821** [TerraformersMC/Terraform#65]
The `ExtendedLeavesBlock` class defines `distance` and `persistent` properties to match the vanilla `LeavesBlock` class:

https://github.com/TerraformersMC/Terraform/blob/5bbff1ac333469cc232d5b7714edfe3d75f11591/terraform-wood-api-v1/src/main/java/com/terraformersmc/terraform/leaves/block/ExtendedLeavesBlock.java#L108-L111

However, as of Minecraft 1.19, leaves can be waterlogged. While the vanilla `LeavesBlock` class defines the `waterlogged` property, the `ExtendedLeavesBlock` class still does not.

**Comment by gniftygnome** [comment]
Resolved by #73.
