### ISSUE TITLE
Crash on Quilt caused by terraform-wood-api

### ISSUE THREAD

**Issue by koelle25** [TerraformersMC/Terraform#71]
Hi there,

I tried to load `traverse-6.1.2` (for MC 1.19.3) via Quilt Modloader `0.18.1-beta25` (with `qfapi-5.0.0-alpha.6_qsl-4.0.0-beta.2_fapi-0.69.1`). Crashes with these errors/logs:
- [crash-2022-12-20_17.34.09-client.txt](https://www.klgrth.io/paste/ejnzd)
- [latest.log](https://www.klgrth.io/paste/v3dzr)

Does not happen on Fabric Loader (`0.14.11` with `fabric-api-0.69.1`).

Any idea what could be the reason (and fix)? I already looked at [net.minecraft.entity.data.TrackedDataHandlerRegistry](https://maven.fabricmc.net/docs/yarn-1.19.3+build.4/net/minecraft/entity/data/TrackedDataHandlerRegistry.html), but there is no `set()` function (as the error message is suggesting to use).

**Comment by JieningYu** [comment]
https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19.3/library/entity/entity_networking/src/main/java/org/quiltmc/qsl/entity/networking/api/tracked_data/QuiltTrackedDataHandlerRegistry.java

**Comment by gniftygnome** [comment]
That is a Quilt API, so switching to use that API would not be Fabric compatible...

**Comment by RoonMoonlight** [comment]
> That is a Quilt API, so switching to use that API would not be Fabric compatible...

There is Quilted Fabric API, but need additional work to make it compatible with Quilt as well

**Comment by gniftygnome** [comment]
I often see claims Fabric mods are compatible with Quilt as long as they aren't using Fabric internals, which we aren't doing here, so I consider this kind of result to be a bug in Quilt (in QFAPI specifically).

I don't have the requisite combination of time and motivation at the moment to either produce a Quilt-specific version of Terraform API or add logic to Terraform API to register things differently depending on which loader is active.  If somebody else wants to contribute work on a Quilt release, I believe Terraformers would be happy to accept it, subject to code quality review.

**Comment by gniftygnome** [comment]
Note, according to https://github.com/TerraformersMC/Traverse/issues/95#issuecomment-1399414940

This will be fixed by https://github.com/QuiltMC/quilt-standard-libraries/pull/253

**Comment by gniftygnome** [comment]
I haven't heard any more about this in a while and hopefully the Quilt fix means everybody is happy.

**Comment by koelle25** [comment]
Yes indeed, it is working fine for some time now :blush: Thanks for looking into this anyway while not being an issue on your side :+1:
