### ISSUE TITLE
Game crashing when a mod using Terraformers Wood Api is present

### ISSUE THREAD

**Issue by DakotaPride** [TerraformersMC/Terraform#74]
Crash Report:
[Crash Report (Pastebin)](https://pastebin.com/DVzWDDpa)

My mod (Hibernal Herbs) utilizes several things from this Api, with the only issue seemingly being the LeafPileBlock. Is there an external library that players must download in order to use the mod that I've missed? Let me know if I can provide any more information in regards to this issue. Thank you!

edit: I'm on 1.19.2 btw

**Comment by DakotaPride** [comment]
I think I fixed it. I just needed to add "include "com.terraformersmc.terraform-api:terraform-wood-api-v1:4.2.0"" as well to build.gradle (doesn't seem to be listed on here for some reason)

**Comment by gniftygnome** [comment]
Yeah, you are free to include it (as you did) or to declare a dependency on it and tell your users to include it in their mod pack ... I think this was just intended to leave the choice up to you (but I doubt anybody who uses Terraform API modules does the latter in practice.).  :)
