### ISSUE TITLE
Impossible to use another WoodType for signs.

### ISSUE THREAD

**Issue by Brandcraf06** [TerraformersMC/Terraform#75]
That's impossible to use another WoodType (Cherry/Bamboo/Crimson for example). Because the terraform signs/hanging signs seems to be in WoodType.OAK only. 

This prevents, in particular, to use some sounds (like _bamboo_wood_hanging_sign_)

**Comment by gniftygnome** [comment]
Yeah, for 1.19.4 and above we should probably add some factories for the different wood types and a second constructor that accepts the type.

**Comment by haykam821** [comment]
This seems to be a regression from Minecraft 1.19.3, where the sound group was not overridden in the sign block constructor. Since Terraform doesn't use wood types, a less invasive fix would be to use the sound group from the block settings instead of the wood type.

**Comment by gniftygnome** [comment]
Well, Mojang changed their constructor from SignType to WoodType and bundled this extra stuff in there, right?  I wouldn't blame the guy who followed that change on our end.  ;)

**Comment by haykam821** [comment]
I've fixed the issue of block sound groups being overridden in 9565fbd2f1acade95e7e2a3230392eae3353120c, but since the detail of always using `WoodType.OAK` persists, I'm leaving this issue open.
