### ISSUE TITLE
Pre-launch entrypoint to initialize MixinExtras is unnecessary

### ISSUE THREAD

**Issue by haykam821** [TerraformersMC/Terraform#76]
Since the bundled version of MixinExtras that initializes on its own should be used, the pre-launch entrypoint that calls `MixinExtrasBootstrap.init()` is not needed.

**Comment by gniftygnome** [comment]
Are you saying the MixinExtras usage instructions are incorrect?  The MixinExtras documentation is unambiguous about this:
https://github.com/LlamaLad7/MixinExtras#initialization

**Comment by gniftygnome** [comment]
I poked around in the source for 0.2.0-beta.5 a bit and nothing jumps out to me as triggering registration on its own.  I think without the init() call the game will run and appear to work but the MixinExtras mixins will not be applied, so unless you have tested that specific functionality it might be hard to tell anything is wrong.

**Comment by haykam821** [comment]
The [new documentation](https://gist.github.com/LlamaLad7/ec597b6d02d39b8a2e35559f9fcce42f) indicates that calling `MixinExtrasBootstrap.init()` isn't necessary, since it's called [here](https://github.com/LlamaLad7/MixinExtras/blob/518e30f09611d35150206572bafab5a732012c8c/fabric/src/main/java/com/llamalad7/mixinextras/platform/fabric/MixinExtrasConfigPlugin.java#L14).

**Comment by gniftygnome** [comment]
I see ... apparently I should have paid more attention to what the upgrade from 0.2.0-beta.4 to 0.2.0-beta.5 entailed.  I had not intended to increase our minimum Fabric Loader version in 1.19.  :(

**Comment by gniftygnome** [comment]
Resolved in 7.0.0-beta.1.
