### ISSUE TITLE
wood-api sign crash (Natures Spirit)

### ISSUE THREAD

**Issue by sleepy-evelyn** [TerraformersMC/Terraform#81]
The wood api causes a crash when using [Natures Spirit](https://github.com/Team-Hibiscus/NatureSpirit). I'm not entirely sure which end needs to be fixed yet but I'll show you where it happens, why, the log and versions.

**Quilt Loader**: 0.21.1-beta2
**MC Version:** 1.20.1
**Natures Spirit version:** 1.1
**Wood api version:** wood-api-v1-7.0.1 (jar-in-jar dependency from Blockus)
**Crash Log:** https://bytebin.lucko.me/1D2N7EE9sA

**To Reproduce**: Place any Natures Spirit sign down

**Location of the crash**: https://github.com/TerraformersMC/Terraform/blob/7783a401d60b2b1bb8398207bb97018a5f3e86b6/terraform-wood-api-v1/src/main/java/com/terraformersmc/terraform/sign/mixin/MixinSignBlockEntityRenderer.java#L33

**Comment by sleepy-evelyn** [comment]
Never mind I removed all the wood-api mods and I still have the issue. It's bizarre.

**Comment by haykam821** [comment]
I think Terraform Wood API v1's mixin obfuscates the actual error, which is that a mod is not registering their sign to the `TexturedRenderLayers.SIGN_TYPE_TEXTURES` map causing the sprite identifier to be null. In theory, signs registered with this API should never have a null sprite identifier as long as the trick used to get the block entity as context is not affected by another mixin.

**Comment by Eko-byte** [comment]
oh wait, this helps thank you
