### ISSUE TITLE
Will this work in snapshots?

### ISSUE THREAD

**Issue by Danjhop4** [TerraformersMC/Terraform#85]
Title says it all

**Comment by gniftygnome** [comment]
Terraform API should work on any snapshot mentioned in the changelog (f.e. on the GitHub releases page).  The API is actively developed and used in our mods.  Often it is released during the snapshots and updated as necessary for testing activity during the snapshot series.  We do not typically set specific version constraints in the API's mod metadata (although the recent release does require Fabric Loader 0.15 or higher).  If you have a question about a specific snapshot version or need it to work on a specific version, you can ask here or in our Discord channel.  https://discord.gg/28DcYE6R

**Comment by Danjhop4** [comment]
Cool I hear you do noise based biomes 
Yes I realise now it’s a sub mod
