### ISSUE TITLE
Regions Unexplored is incompatible with Terraform Dirt API MixinEatGrassGoal

### ISSUE THREAD

**Issue by gniftygnome** [TerraformersMC/Terraform#86]
At least on Forge and probably also on Fabric, Regions Unexplored has a mixin which prevents our MixinEatGrassGoal from applying because it replaces the entire method we target.

Mixin in question:
https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/1.20.1/src/main/java/net/regions_unexplored/mixin/EatBlockGoalMixin.java#L53

Ours:
https://github.com/TerraformersMC/Terraform/blob/1.20.3/terraform-dirt-api-v1/src/main/java/com/terraformersmc/terraform/dirt/mixin/MixinEatGrassGoal.java#L33

This appears to already be known to the RU devs:
https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/80

**Comment by KirboSoftware** [comment]
This issue should be fixed in the following releases of regions unexplored:
Forge: 0.5.3.1
Fabric: 0.5.3.3

Which are just released 👍

**Comment by gniftygnome** [comment]
Sweet!  I'll resolve this.
