### ISSUE TITLE
FIXED Terraformers Probably Causing that I cant Join My own Server with the Same mods FIXED

### ISSUE THREAD

**Issue by Edin63** [TerraformersMC/Terraform#89]
FIXED
I have already asked in your discord, the discord from fabric and the Create extra discord from where I Build up My own modpack but only the one from the fabric discord could help me 

the apple (yes from the fabricord) said
> this is probably **TrackedDataRegistry desync**.
And this is the only Information anyone could give me about this Error I have
——
**Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx:12, widx: 12, cap:12/13)** 
——
This is My minecraft Client log **https://mclo.gs/fEqRDPu**
This is My Server log **https://mclo.gs/RA1LK0f**

I appreciate any try of help 🧌
FIXED 
Solution= i just had the wrong version of spell engine (0.12.3 Fabric and now i have 0.12.5 Fabric)

**Comment by gniftygnome** [comment]
Thanks for the update.
