### ISSUE TITLE
wood api causes problems in datagen

### ISSUE THREAD

**Issue by z3roco01** [TerraformersMC/Terraform#92]
when i try to run data gen with the wood api it gives the error `Mod 'Terraform Wood API (v1)' (terraform-wood-api-v1) 10.0.0 requires any version of fabric-rendering-v1, which is missing!`

**Comment by gniftygnome** [comment]
I think they removed v1.  Need to check if we actually need it, remove if not, v2 (I think) if so.

**Comment by z3roco01** [comment]
it also causes a bunch of class not found/error loading class errors in the client, all the errors it causes: [https://pastebin.com/PD4Pbcfs](https://pastebin.com/PD4Pbcfs)

**Comment by haykam821** [comment]
Could you post a full game log? This issue may be caused by a version mismatch of some sort.

**Comment by z3roco01** [comment]
i just realised it is, i was using 10.0.0 when im on minecraft 1.20.4, i switched to 9.0.0 and the client works but the data gen error is still there

**Comment by gniftygnome** [comment]
> the client works but the data gen error is still there

We really need the logs, then.  Otherwise we don't know how to reproduce the problem.

**Comment by z3roco01** [comment]
datagen doesnt make any logs, or none that i can find, this is all that it outputs [https://pastebin.com/RkRvHXXf](https://pastebin.com/RkRvHXXf)

**Comment by gniftygnome** [comment]
How are you running datagen?  What Loom version is involved?

**Comment by z3roco01** [comment]
im running it with the intellij idea configuration, its loom 1.6-SNAPSHOT

**Comment by gniftygnome** [comment]
The log from datagen should be somewhere like `IdeaProjects/YourMod/build/datagen/logs/debug.log` (but with Windows-y paths if you're on Windows, and with your mod's name, not YourMod).

**Comment by z3roco01** [comment]
here it is [https://pastebin.com/GKzT5cpn](https://pastebin.com/GKzT5cpn)

**Comment by gniftygnome** [comment]
I'm pretty much stumped on this.  I think it's an issue with gradle config or maybe something about the Loom version ... you might have better luck in the Fabric discord, probably #mod-dev-gradle-ides

**Comment by z3roco01** [comment]
ill try there, thanks for the help !

**Comment by z3roco01** [comment]
for anyone finding with the same problem, you need too add
```gradle
loom {
    runs {
        datagen {
            inherit client
        }
    }
}
```
to your `build.gradle` and also make sure `fabricApi` is before `loom`

**Comment by z3roco01** [comment]
you also have to delete `.idea` and restart idea to get the datagen configuration to work
