### ISSUE TITLE
TerraformBoatTypeRegistry using private method

### ISSUE THREAD

**Issue by Pilot-Boi** [TerraformersMC/Terraform#93]
The Identifier method used in TerraformBoatTypeRegistry to create an Identifier was recently made private by Mojang, so the compiler is now throwing an error. Request that the method call when creating REGISTRY_ID be changed from "new Identifier("terraform", "boat")" to "Identifier.of("terraform", "boat") This won't throw an error on compiling.

**Comment by haykam821** [comment]
This issue should already be fixed in version 11.0.0 alpha 1; are you using that version?

**Comment by Pilot-Boi** [comment]
I'm using 10.0.0 because I couldn't figure out how to write the import command in the build file. I'm really new to modding
