### ISSUE TITLE
Terraform for 1.21.4

### ISSUE THREAD

**Issue by JCS-Mecabricks** [TerraformersMC/Terraform#98]
I have a mod that uses terraform as a dependency. Now that 1.21.4 came out, I wanted to know if you will be making terraform for 1.21.4. I would really appreciate it if you did and gave a telease date.

**Comment by gniftygnome** [comment]
Terraform API version 13.0.0-alpha.1 for 1.21.4 was released on the 3rd.  I expect eventually 13.0.0 will be released without changes, so you might as well use the alpha release.

**Comment by JCS-Mecabricks** [comment]
Isn't that 1.21.4 pre-release?

**Comment by gniftygnome** [comment]
> Isn't that 1.21.4 pre-release?

Nah; I tested it when 1.21.4 released and it was fine.  That's why we haven't been in a big hurry to make another release.  Mainly right now the reason it's still alpha is we're just waiting a while in case there's feedback about bugs or we need to change the API to make it better.
